#!/usr/bin/env bash
# Install and run Dictation V2 from an external content pack on Ubuntu.

set -Eeuo pipefail
IFS=$'\n\t'

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"
REPO_ROOT="$(cd -- "$SCRIPT_DIR/.." && pwd -P)"
ENV_FILE="$SCRIPT_DIR/local.env"

C_OK=$'\033[32m'; C_WARN=$'\033[33m'; C_ERR=$'\033[31m'
C_HEAD=$'\033[1;36m'; C_OFF=$'\033[0m'
step() { printf '\n%s==> %s%s\n' "$C_HEAD" "$*" "$C_OFF"; }
ok() { printf '%s  [OK]%s %s\n' "$C_OK" "$C_OFF" "$*"; }
warn() { printf '%s  [!] %s%s\n' "$C_WARN" "$C_OFF" "$*"; }
die() { printf '%s  [X] %s%s\n' "$C_ERR" "$*" "$C_OFF" >&2; exit 1; }

SERVE=no
INSTALL_SERVICE=no
UNINSTALL_SERVICE=no
CHECK_ONLY=no
while [[ $# -gt 0 ]]; do
  case "$1" in
    --serve) SERVE=yes; shift ;;
    --install-service) INSTALL_SERVICE=yes; shift ;;
    --uninstall-service) UNINSTALL_SERVICE=yes; shift ;;
    --check-only) CHECK_ONLY=yes; shift ;;
    -h|--help)
      printf '%s\n' \
        'Usage: bash deploy/local-install.sh [option]' \
        '  --serve              install, then run V2 in the foreground' \
        '  --install-service    install/update the dictation-local-v2 service' \
        '  --uninstall-service  remove that service; keep all state' \
        '  --check-only         validate program and content without installing'
      exit 0 ;;
    *) die "未知参数: $1" ;;
  esac
done

if [[ "$UNINSTALL_SERVICE" == "yes" ]]; then
  step "移除本地 V2 服务"
  command -v systemctl >/dev/null 2>&1 || die "本机没有 systemd"
  sudo systemctl disable --now dictation-local-v2 >/dev/null 2>&1 || true
  sudo rm -f /etc/systemd/system/dictation-local-v2.service
  sudo systemctl daemon-reload
  ok "服务已移除；数据库、录音和内容包未删除"
  exit 0
fi

if [[ -f "$ENV_FILE" ]]; then
  set -a
  # shellcheck disable=SC1090
  . "$ENV_FILE"
  set +a
else
  warn "未找到 deploy/local.env，使用默认的相邻仓库布局"
fi

: "${CONTENT_ROOT:=../dictation-content/packs/zh-cn/primary-3a}"
: "${STATE_ROOT:=.runtime/local}"
: "${V2_PORT:=8889}"
: "${BIND_HOST:=127.0.0.1}"
: "${APP_TIMEZONE:=Asia/Shanghai}"
: "${STUDIO_ENABLED:=1}"

[[ "$CONTENT_ROOT" == /* ]] || CONTENT_ROOT="$REPO_ROOT/$CONTENT_ROOT"
[[ "$STATE_ROOT" == /* ]] || STATE_ROOT="$REPO_ROOT/$STATE_ROOT"
CONTENT_ROOT="$(realpath -m -- "$CONTENT_ROOT")"
STATE_ROOT="$(realpath -m -- "$STATE_ROOT")"
WEB_ROOT="$STATE_ROOT/web"
DB_PATH="$STATE_ROOT/v2/dictation.db"
RUNTIME_ENV="$STATE_ROOT/v2.env"
AUDIO_TOOL="$REPO_ROOT/shared/tools/audio_bundle.py"

[[ "$BIND_HOST" == "127.0.0.1" || "$BIND_HOST" == "0.0.0.0" ]] \
  || die "BIND_HOST 只能是 127.0.0.1 或 0.0.0.0"
[[ "$STUDIO_ENABLED" == "0" || "$STUDIO_ENABLED" == "1" ]] \
  || die "STUDIO_ENABLED 只能是 0 或 1"
[[ "$V2_PORT" =~ ^[0-9]+$ ]] && (( V2_PORT >= 1 && V2_PORT <= 65535 )) \
  || die "V2_PORT 必须是 1..65535"

step "检查程序与外部内容包"
command -v python3 >/dev/null 2>&1 || die "缺少 python3"
python3 "$REPO_ROOT/shared/content_pack.py" "$CONTENT_ROOT" \
  || die "内容包无效: $CONTENT_ROOT"
DICTATION_CONTENT_ROOT="$CONTENT_ROOT" \
  python3 "$AUDIO_TOOL" verify-dataset --content-root "$CONTENT_ROOT" \
  || die "内容包音频未通过校验"
python3 -m compileall -q "$REPO_ROOT/v2" "$REPO_ROOT/shared"
ok "程序与内容包通过静态检查"

if [[ "$CHECK_ONLY" == "yes" ]]; then
  exit 0
fi

step "检查系统依赖"
MISSING=()
python3 -c 'import venv' >/dev/null 2>&1 || MISSING+=(python3-venv)
command -v ffmpeg >/dev/null 2>&1 || MISSING+=(ffmpeg)
if (( ${#MISSING[@]} > 0 )); then
  command -v apt-get >/dev/null 2>&1 || die "缺少系统包: ${MISSING[*]}"
  command -v sudo >/dev/null 2>&1 || die "需要 sudo 安装系统包: ${MISSING[*]}"
  sudo apt-get update -qq
  sudo apt-get install -y "${MISSING[@]}"
fi
ok "Python 与 ffmpeg 已就绪"

step "安装 V2 Python 依赖"
VENV="$REPO_ROOT/v2/venv"
if [[ ! -x "$VENV/bin/python" ]]; then
  python3 -m venv "$VENV"
fi
"$VENV/bin/pip" install --quiet --upgrade pip
"$VENV/bin/pip" install --quiet -r "$REPO_ROOT/v2/requirements.txt"
"$VENV/bin/pip" check >/dev/null
ok "V2 依赖一致"

step "同步数据库与运行时静态资源"
mkdir -p "$STATE_ROOT/v2" "$WEB_ROOT"
if [[ -f "$DB_PATH" ]]; then
  "$VENV/bin/python" "$REPO_ROOT/shared/tools/migrate_poly_ids.py" "$DB_PATH" >/dev/null
  "$VENV/bin/python" "$REPO_ROOT/shared/sync_content.py" \
    --db "$DB_PATH" --content-root "$CONTENT_ROOT"
else
  "$VENV/bin/python" "$REPO_ROOT/shared/init_db.py" \
    --db "$DB_PATH" --content-root "$CONTENT_ROOT"
fi
DICTATION_CONTENT_ROOT="$CONTENT_ROOT" \
  "$VENV/bin/python" "$REPO_ROOT/tools/stage.py" v2 \
    --content-root "$CONTENT_ROOT" --web-root "$WEB_ROOT"
DICTATION_CONTENT_ROOT="$CONTENT_ROOT" \
  "$VENV/bin/python" "$AUDIO_TOOL" inventory --audio-dir "$WEB_ROOT/audio" >/dev/null
ok "数据库、前端和音频已经就位"

write_env_value() {
  local key="$1" value="$2"
  value="${value//\\/\\\\}"
  value="${value//\"/\\\"}"
  printf '%s="%s"\n' "$key" "$value"
}

{
  printf '# Generated by deploy/local-install.sh\n'
  write_env_value DICTATION_CONTENT_ROOT "$CONTENT_ROOT"
  write_env_value DICTATION_DB "$DB_PATH"
  write_env_value WEB_ROOT "$WEB_ROOT"
  write_env_value STUDIO_AUDIO_DIR "$WEB_ROOT/audio/w"
  write_env_value APP_TIMEZONE "$APP_TIMEZONE"
  printf 'STUDIO_ENABLED=%s\n' "$STUDIO_ENABLED"
} > "$RUNTIME_ENV"
chmod 600 "$RUNTIME_ENV"
ok "运行配置: $RUNTIME_ENV"

if [[ "$INSTALL_SERVICE" == "yes" ]]; then
  step "安装本地 systemd 服务"
  command -v systemctl >/dev/null 2>&1 || die "本机没有 systemd"
  RUN_USER="$(id -un)"
  RUN_GROUP="$(id -gn)"
  TEMP_UNIT="$(mktemp)"
  trap 'rm -f -- "$TEMP_UNIT"' EXIT
  {
    printf '%s\n' \
      '[Unit]' \
      'Description=Dictation V2 local service' \
      'After=network.target' \
      '' \
      '[Service]' \
      'Type=simple' \
      "User=$RUN_USER" \
      "Group=$RUN_GROUP" \
      "WorkingDirectory=$REPO_ROOT/v2" \
      "EnvironmentFile=$RUNTIME_ENV" \
      "ExecStart=$VENV/bin/uvicorn main:app --host $BIND_HOST --port $V2_PORT" \
      'Restart=on-failure' \
      'RestartSec=5' \
      'NoNewPrivileges=true' \
      '' \
      '[Install]' \
      'WantedBy=multi-user.target'
  } > "$TEMP_UNIT"
  sudo install -m 0644 "$TEMP_UNIT" /etc/systemd/system/dictation-local-v2.service
  sudo systemctl daemon-reload
  sudo systemctl enable --now dictation-local-v2
  ok "dictation-local-v2 已启动"
fi

printf '\n%s本地 V2 部署完成%s\n' "$C_OK" "$C_OFF"
printf '  内容包: %s\n' "$CONTENT_ROOT"
printf '  运行状态: %s\n' "$STATE_ROOT"
printf '  访问地址: http://localhost:%s\n' "$V2_PORT"

if [[ "$BIND_HOST" == "0.0.0.0" ]]; then
  warn "服务对局域网开放；应用本身没有访问鉴权"
fi

if [[ "$SERVE" == "yes" ]]; then
  step "启动 V2（Ctrl+C 结束）"
  set -a
  # shellcheck disable=SC1090
  . "$RUNTIME_ENV"
  set +a
  cd "$REPO_ROOT/v2"
  exec "$VENV/bin/uvicorn" main:app --reload --host "$BIND_HOST" --port "$V2_PORT"
fi
