#!/usr/bin/env python3
"""Export a validated content pack to Cloudflare D1 SQL.

The static lesson seed remains a Wrangler migration. Runtime settings are
written separately and applied on every deployment, so changing content packs
does not require editing Worker source code or inventing a new migration.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys


TOOLS_DIR = Path(__file__).resolve().parent
SHARED_DIR = TOOLS_DIR.parent
ROOT = SHARED_DIR.parent
sys.path.insert(0, str(SHARED_DIR))

from content_pack import (  # noqa: E402
    ContentPackError,
    DEFAULT_CONTENT_ROOT,
    load_content_pack,
)


DEFAULT_SEED = ROOT / "v3" / "migrations" / "0002_seed.sql"
DEFAULT_RUNTIME = ROOT / "v3" / ".content-runtime.sql"


def q(value: object) -> str:
    """Escape a value as a SQLite string literal."""
    return "'" + str(value).replace("'", "''") + "'"


def seed_sql(pack) -> str:
    lines = [
        "-- D1 static seed generated by shared/tools/export_d1.py; do not edit",
        f"-- content pack: {pack.id} ({pack.dataset_sha256})",
        "",
        "-- lessons",
    ]
    for lesson in pack.lessons:
        lines.append(
            "INSERT OR IGNORE INTO lessons "
            "(lesson_seq, unit_id, unit_name, lesson_title, lesson_name) VALUES "
            f"({lesson['lesson_seq']}, {lesson['unit_id']}, "
            f"{q(lesson['unit_name'])}, {q(lesson.get('lesson_title', ''))}, "
            f"{q(lesson['lesson_name'])});"
        )
    lines.append(f"-- {len(pack.lessons)} lessons\n")

    lines.append("-- knowledge_points")
    for point in pack.knowledge_points:
        options = json.dumps(point["options_json"], ensure_ascii=False)
        lines.append(
            "INSERT OR IGNORE INTO knowledge_points "
            "(lesson_seq, target, category, options_json) VALUES "
            f"({point['lesson_seq']}, {q(point['target'])}, "
            f"{q(point['category'])}, {q(options)});"
        )
    lines.append(f"-- {len(pack.knowledge_points)} knowledge points\n")
    lines.append("-- initial single-user progress")
    lines.append(
        "INSERT OR IGNORE INTO user_progress (user_id, current_lesson_seq) "
        f"VALUES (1, {pack.runtime.initial_lesson});"
    )
    return "\n".join(lines) + "\n"


def runtime_sql(pack) -> str:
    runtime = pack.runtime
    cold = "NULL" if runtime.cold_start_lesson is None else str(runtime.cold_start_lesson)
    reviews = json.dumps(sorted(runtime.review_lessons), separators=(",", ":"))
    return "\n".join(
        (
            "-- D1 content runtime generated by shared/tools/export_d1.py; do not edit",
            "INSERT OR REPLACE INTO content_runtime (",
            "  singleton, pack_id, display_name, dataset_sha256, cold_start_lesson,",
            "  initial_lesson, review_lessons_json, daily_target, review_target,",
            "  polyphonic_per_lesson",
            ") VALUES (",
            f"  1, {q(pack.id)}, {q(pack.display_name)}, {q(pack.dataset_sha256)}, {cold},",
            f"  {runtime.initial_lesson}, {q(reviews)}, {runtime.daily_target},",
            f"  {runtime.review_target}, {runtime.polyphonic_per_lesson}",
            ");",
            "",
        )
    )


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--content-root", type=Path, default=DEFAULT_CONTENT_ROOT)
    parser.add_argument("--output", type=Path, default=DEFAULT_SEED)
    parser.add_argument("--runtime-output", type=Path, default=DEFAULT_RUNTIME)
    args = parser.parse_args()

    try:
        pack = load_content_pack(args.content_root)
    except ContentPackError as exc:
        print(f"[X] 内容包校验失败: {exc}", file=sys.stderr)
        return 1

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.runtime_output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(seed_sql(pack), encoding="utf-8")
    args.runtime_output.write_text(runtime_sql(pack), encoding="utf-8")
    print(f"[OK] D1 种子: {args.output}")
    print(f"     {len(pack.lessons)} 门课程, {len(pack.knowledge_points)} 条知识点")
    print(f"[OK] D1 运行时: {args.runtime_output} ({pack.id})")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
